# General setup
# -------------
language: python
python:
    - "2.7"
# Allows the python virtualenv to use apt-get installed packages, which
# is essential (as ROS recommends this and pip doesn't seem to contain
# all packages, or contains them with errors).
virtualenv:
    system_site_packages: true
# Allow caching of debian (apt-get) packages. This means they're cached
# on Travis, so we still have to download/install them, but it will be
# faster than going to the ubuntu repositories.
cache: apt
# Before anything, see if we can get the mongoDB troubles out of the way.
# Note that this is a Travis-CI specific problem; this is not needed in
# general.
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
    - sudo apt-get --purge remove mongodb-10gen postgresql-9.2 postgresql-contrib-9.2 postgresql-9.3 postgresql-contrib-9.3
  - export ROS_DISTRO=hydro
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
# Settings to make installing script more general.
  - export ROS_CI_DESKTOP=`lsb_release -cs`  # e.g. 'precise'
  - export ROS_CI_PREFIX=ros-${ROS_DISTRO}-  # e.g. 'ros-groovy-'

notifications:
  email: false

# Commands to install dependencies
# --------------------------------
install:
  # Install ROS
  - echo "deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main" | sudo tee /etc/apt/sources.list.d/ros-latest.list
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros
  # Setup rosdep
  - sudo rosdep init
  - rosdep update
  # Install catkin_tools
  - pip install -U catkin_tools
  # Create workspace.
  - mkdir -p ~/catkin_ws/src
  - cd ..; mv rapid_robot ~/catkin_ws/src
  # Install dependencies
  - rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y
  # Build
  - cd ~/catkin_ws/
  - catkin init
  - catkin build
  #- curl https://install.meteor.com/ | sh

# Command to run tests
# --------------------
before_script:
  - source /opt/ros/$ROS_DISTRO/setup.bash

script:
  - catkin build
# Real tests: crash because of Gazebo bugs
#    - roslaunch pr2_pbd_interaction simulated_robot.launch gui:=false
# Debug: trying to just run gazebo's table object launch (Gazebo bugs)
#    - rostest pr2_pbd_interaction test_endtoend.test
# Linter: last resort to getting *something* useful to run on Travis :-)
# NOTE(mbforbes): Add more files to this as they're completed.
#    - roscd pr2_pbd_interaction
#    - pep8 src/*.py test/*.py nodes/*.py
